plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-compress-images

# Site settings
title: Honor & Mitchell
email: hare.lachat.wedding@proton.me
url: http://wedding.hare-lachat.com
# description: "We're getting married and can't wait to celebrate with you!"
baseurl: "" #"/weddings/sample"

collections:
  stories:
    sort_by: order
  modals:
  banners:

sass:
  style: compressed

defaults:
  - scope:
      path: "photos/"
    values:
      image: true
  - scope:
      path: banners
    values:
      layout: banner

# Build settings
markdown: kramdown
permalink: pretty

exclude:
  - _compress_images_cache.yml

compress_images:
  images_path: "{assets,photos}/**/*.{gif,png,jpg,jpeg,svg}"

theme: jekyll-theme-easy-wedding